branchName: short
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueMilestoneToPR: true
branches:
  - label: 機能強化
    prefix: feature/${issue.user.login}/
  - label: バグ
    prefix: bugfix/${issue.user.login}/
  - label: '*'
    prefix: issues/
  - label: 助けが必要
    skip: true